[project]
name = "us-imputation-benchmarking"
version = "0.1.0"
description = "Benchmarking imputation models for US household survey data"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "scipy",
    "rpy2",
    "requests",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "flake8",
    "black",
    "isort",
    "mypy",
]