title: MicroImpute documentation
author: PolicyEngine
logo: logo.png

execute:
  execute_notebooks: force

repository:
  url: https://github.com/policyengine/microimpute
  branch: main
  path_to_book: docs

sphinx:
  config:
    suppress_warnings: [""]
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme: furo
    pygments_style: default
    html_css_files:
      - style.css
  extra_extensions:
    - "sphinx.ext.autodoc"
    #- "sphinxarg.ext"
    - "sphinx.ext.viewcode"
    - "sphinx.ext.napoleon"
    #- "sphinx_math_dollar"
    - "sphinx.ext.mathjax"
