title: MicroImpute
author: PolicyEngine

execute:
  execute_notebooks: force

repository:
  url: https://github.com/policyengine/us-imputation-benchmarking
  branch: main
  path_to_book: docs

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme: sphinx_book_theme
    pygments_style: default
