name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.x'
    
    - name: Install R dependencies
      run: |
        install.packages(c("StatMatch"))
      shell: Rscript {0}
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[dev]
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Test with pytest
      run: |
        # For now, just run the existing tests.py script
        # Later, this should be replaced with proper pytest
        python us_imputation_benchmarking/tests.py