name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.11'
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.x'
    
    - name: Install R dependencies
      run: |
        install.packages(c("StatMatch"))
      shell: Rscript {0}
    
    - name: Install Python dependencies
      run: uv pip install -e .[dev] --system
    
    - name: Test with pytest
      run: make test
