name: CI

on:
  push:
    branches: [ main ]

jobs:
  Test:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install R and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base r-base-dev libtirpc-dev
      - name: Install R packages
        run: |
          sudo Rscript -e 'install.packages("StatMatch", repos="https://cloud.r-project.org")'
      - name: Install Python dependencies
        run: |
          uv pip install -e ".[dev]" --system
      - name: Run tests with coverage
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
